import type { Unit } from "./types";

export const COURSE_A1: Unit[] = [
  {
    id: "first-words",
    title: "Första orden",
    titleDe: "Die ersten Wörter",
    emoji: "👋",
    level: "A1",
    blurb: "Greet people, say your name, and be politely Swedish from day one.",
    lessons: [
      {
        id: "hello",
        title: "Hej!",
        titleDe: "Begrüßung",
        intro:
          "Swedish greetings are refreshingly simple. 'Hej' works for everyone at any hour — your boss, a stranger, a five-year-old. There is no Swedish equivalent of the German formality ladder, so you can stop worrying about Sie versus du entirely.",
        words: ["hej", "hej då", "god morgon", "god kväll", "tack", "varsågod", "ja", "nej", "förlåt", "ursäkta", "vi ses", "ha det bra"],
        exercises: [
          {
            kind: "choice",
            prompt: "You walk into a shop at 3pm. What do you say?",
            options: ["God morgon", "Hej", "God natt", "Hej då"],
            answer: 1,
            explain: "'Hej' is correct at any time of day. 'God morgon' is only for mornings, and even then 'hej' is more common.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Danke!",
            answer: "Tack",
            alts: ["tack så mycket", "tack!"],
          },
          {
            kind: "choice",
            prompt: "Which word do you use to apologise for stepping on someone's foot?",
            options: ["Ursäkta", "Förlåt", "Varsågod", "Tack"],
            answer: 1,
            explain: "'Förlåt' apologises for something you did. 'Ursäkta' gets someone's attention or excuses you as you squeeze past.",
          },
          {
            kind: "listen",
            sv: "Hej, hur mår du?",
            de: "Hallo, wie geht es dir?",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Tschüss!",
            answer: "Hej då",
            alts: ["hejdå", "vi ses"],
          },
          {
            kind: "speak",
            sv: "Hej! Tack så mycket.",
            de: "Hallo! Vielen Dank.",
          },
        ],
      },
      {
        id: "introductions",
        title: "Vad heter du?",
        titleDe: "Sich vorstellen",
        intro:
          "Swedish uses 'heta' — literally 'to be called' — exactly like German 'heißen'. And 'jag kommer från' works just like 'ich komme aus'. This lesson is mostly free for you.",
        grammarId: "present-tense",
        words: ["heta", "jag heter", "vad heter du", "komma", "jag kommer från", "var kommer du ifrån", "bo", "trevligt att träffas", "namn", "efternamn"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich heiße Tiffy.",
            answer: "Jag heter Tiffy",
            hint: "heta → heter",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wie heißt du?",
            answer: "Vad heter du",
            explain: "Swedish asks 'what are you called', so it's 'vad', not 'hur'.",
          },
          {
            kind: "blank",
            prompt: "Jag ___ från Tyskland.",
            answer: "kommer",
            explain: "'komma' → 'kommer'. Remember: one form for every person.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich wohne in Berlin.",
            answer: "Jag bor i Berlin",
            hint: "bo → bor",
          },
          {
            kind: "choice",
            prompt: "Which is correct?",
            options: ["Jag heta Anna", "Jag heter Anna", "Jag hetar Anna", "Jag är heter Anna"],
            answer: 1,
            explain: "'heta' is a group 2 verb: the present is 'heter'.",
          },
          {
            kind: "order",
            prompt: "Build: 'Where are you from?'",
            tokens: ["Var", "kommer", "du", "ifrån"],
            answer: "Var kommer du ifrån",
            explain: "Question word first, then the verb, then the subject. Same as German.",
          },
          {
            kind: "speak",
            sv: "Hej, jag heter Tiffy. Jag kommer från Tyskland.",
            de: "Hallo, ich heiße Tiffy. Ich komme aus Deutschland.",
          },
        ],
      },
      {
        id: "survival-phrases",
        title: "Överlevnadsfraser",
        titleDe: "Überlebenssätze",
        intro:
          "The sentences that rescue a conversation when you've lost the thread. Learn these before anything else — they buy you time and Swedes will happily slow down for you.",
        words: [
          "jag förstår inte",
          "kan du säga det igen",
          "kan du prata långsammare",
          "vad betyder det",
          "hur säger man",
          "jag vet inte",
          "ursäkta",
          "hjälp",
        ],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich verstehe nicht.",
            answer: "Jag förstår inte",
            explain: "'inte' comes after the verb in a main clause.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Kannst du langsamer sprechen?",
            answer: "Kan du prata långsammare",
          },
          {
            kind: "choice",
            prompt: "You didn't catch a word. What do you ask?",
            options: ["Vad betyder det?", "Vad heter du?", "Hur mår du?", "Var bor du?"],
            answer: 0,
          },
          {
            kind: "listen",
            sv: "Kan du säga det igen, tack?",
            de: "Kannst du das bitte wiederholen?",
          },
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Hur säger man 'Fahrrad' på svenska?",
            answer: "Wie sagt man 'Fahrrad' auf Schwedisch?",
          },
        ],
      },
    ],
  },
  {
    id: "who-are-you",
    title: "Vem är du?",
    titleDe: "Pronomen und sein",
    emoji: "🙋",
    level: "A1",
    blurb: "Pronouns and the verb 'vara'. One verb form for everybody — enjoy it.",
    lessons: [
      {
        id: "pronouns",
        title: "Jag, du, han, hon",
        titleDe: "Personalpronomen",
        intro:
          "Swedish pronouns line up almost perfectly with German. The one thing to watch: 'den' and 'det' both mean 'it', and which one you use depends on the noun's gender.",
        grammarId: "en-ett",
        words: ["jag", "du", "han", "hon", "den", "det", "vi", "ni", "de", "mig", "dig", "honom", "henne", "oss", "dem"],
        exercises: [
          {
            kind: "choice",
            prompt: "The word is 'en bil'. Which pronoun replaces it?",
            options: ["den", "det", "han", "de"],
            answer: 0,
            explain: "en-words are replaced by 'den'. ett-words by 'det'.",
          },
          {
            kind: "choice",
            prompt: "The word is 'ett hus'. Which pronoun replaces it?",
            options: ["den", "det", "hon", "de"],
            answer: 1,
          },
          {
            kind: "blank",
            prompt: "Jag ser ___ (ihn).",
            answer: "honom",
          },
          {
            kind: "blank",
            prompt: "Hon ringer ___ (mich).",
            answer: "mig",
            explain: "Written 'mig', pronounced 'mej'.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wir sehen sie (Plural).",
            answer: "Vi ser dem",
            explain: "'de' is the subject form, 'dem' the object form. Both are said 'dom'.",
          },
        ],
      },
      {
        id: "to-be",
        title: "Att vara",
        titleDe: "Das Verb sein",
        intro:
          "Here is the best news in Swedish grammar. Where German has bin, bist, ist, sind, seid, Swedish has exactly one word: 'är'. It's pronounced like a short 'e'.",
        grammarId: "present-tense",
        words: ["vara", "ha", "trött", "glad", "hungrig", "sjuk", "gammal", "ung"],
        exercises: [
          {
            kind: "choice",
            prompt: "Which is correct for 'du bist'?",
            options: ["du är", "du äst", "du bist", "du varar"],
            answer: 0,
            explain: "Every person uses 'är'. jag är, du är, han är, vi är, ni är, de är.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich bin müde.",
            answer: "Jag är trött",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wir sind hungrig.",
            answer: "Vi är hungriga",
            explain: "The adjective agrees with a plural subject: 'hungrig' → 'hungriga'.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Hast du Zeit?",
            answer: "Har du tid",
          },
          {
            kind: "order",
            prompt: "Build: 'Today I am tired.'",
            tokens: ["Idag", "är", "jag", "trött"],
            answer: "Idag är jag trött",
            explain: "'Idag' takes the first slot, so the subject moves behind the verb. Exactly like German.",
          },
        ],
      },
      {
        id: "questions",
        title: "Frågor",
        titleDe: "Fragen stellen",
        intro:
          "Two question types, both built exactly as in German: put the verb first for yes/no questions, or lead with a question word. No 'do' auxiliary anywhere.",
        grammarId: "questions",
        words: ["vad", "vem", "var", "vart", "när", "hur", "varför", "vilken", "jo"],
        exercises: [
          {
            kind: "order",
            prompt: "Build: 'Do you speak Swedish?'",
            tokens: ["Talar", "du", "svenska"],
            answer: "Talar du svenska",
          },
          {
            kind: "choice",
            prompt: "'Wohin gehst du?' — which question word?",
            options: ["Var", "Vart", "Vem", "När"],
            answer: 1,
            explain: "'var' = wo, 'vart' = wohin. Swedish keeps the distinction German makes.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wo wohnst du?",
            answer: "Var bor du",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Warum kommst du nicht?",
            answer: "Varför kommer du inte",
            explain: "'inte' goes after the verb — but here the subject 'du' is between them.",
          },
          {
            kind: "choice",
            prompt: "— Vill du inte ha kaffe? You DO want coffee. What do you answer?",
            options: ["Ja", "Nej", "Jo", "Tack"],
            answer: 2,
            explain: "Contradicting a negative question needs 'jo', exactly like German 'doch'.",
          },
        ],
      },
    ],
  },
  {
    id: "en-ett-unit",
    title: "En eller ett",
    titleDe: "Die zwei Geschlechter",
    emoji: "⚖️",
    level: "A1",
    blurb: "Two genders instead of three — but you can't guess them from German.",
    lessons: [
      {
        id: "gender",
        title: "En-ord och ett-ord",
        titleDe: "en oder ett",
        intro:
          "Swedish has two genders: en-words (about 75% of nouns) and ett-words. Crucially, the German gender tells you nothing. 'Das Buch' is 'en bok'; 'der Tisch' is 'ett bord'. Always store the article with the word.",
        grammarId: "en-ett",
        words: ["bil", "hus", "bok", "bord", "stol", "barn", "rum", "dörr", "fönster", "väska", "penna", "glas"],
        exercises: [
          {
            kind: "choice",
            prompt: "___ bok",
            options: ["en", "ett"],
            answer: 0,
            explain: "'en bok' — despite German 'das Buch'. Gender doesn't transfer.",
          },
          {
            kind: "choice",
            prompt: "___ bord",
            options: ["en", "ett"],
            answer: 1,
            explain: "'ett bord' — despite German 'der Tisch'.",
          },
          {
            kind: "choice",
            prompt: "___ barn",
            options: ["en", "ett"],
            answer: 1,
          },
          {
            kind: "choice",
            prompt: "___ stol",
            options: ["en", "ett"],
            answer: 0,
          },
          {
            kind: "choice",
            prompt: "You genuinely have no idea what gender a noun is. What's the best guess?",
            options: ["en", "ett"],
            answer: 0,
            explain: "Roughly three quarters of Swedish nouns are en-words, so 'en' is the better bet.",
          },
        ],
      },
      {
        id: "definite",
        title: "Bestämd form",
        titleDe: "Der bestimmte Artikel",
        intro:
          "Swedish glues 'the' onto the end of the word. 'en bil' becomes 'bilen'; 'ett hus' becomes 'huset'. There is no separate word for 'the' in the simple case, which makes Swedish look very different from German on the page.",
        grammarId: "definite-forms",
        words: ["bil", "hus", "flicka", "pojke", "äpple", "vän", "stad", "gata"],
        exercises: [
          {
            kind: "blank",
            prompt: "en bil → ___",
            answer: "bilen",
          },
          {
            kind: "blank",
            prompt: "ett hus → ___",
            answer: "huset",
          },
          {
            kind: "blank",
            prompt: "en flicka → ___",
            answer: "flickan",
            explain: "The noun already ends in a vowel, so you only add -n.",
          },
          {
            kind: "blank",
            prompt: "ett äpple → ___",
            answer: "äpplet",
            explain: "Ends in a vowel, so just -t.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Das Auto ist rot.",
            answer: "Bilen är röd",
          },
          {
            kind: "choice",
            prompt: "How do you say 'the house' in Swedish?",
            options: ["det hus", "huset", "det huset", "en huset"],
            answer: 1,
            explain: "Without an adjective, you only need the suffix.",
          },
        ],
      },
      {
        id: "plurals",
        title: "Plural",
        titleDe: "Mehrzahl",
        intro:
          "Five plural patterns. The one that catches everybody: many ett-words don't change at all. 'Ett barn' and 'tre barn' look identical — only the number tells you.",
        grammarId: "plurals",
        words: ["flicka", "bil", "vän", "äpple", "hus", "barn", "man", "bok", "hand", "fot"],
        exercises: [
          {
            kind: "blank",
            prompt: "en flicka → två ___",
            answer: "flickor",
            explain: "en-words ending in -a take -or.",
          },
          {
            kind: "blank",
            prompt: "en bil → tre ___",
            answer: "bilar",
          },
          {
            kind: "blank",
            prompt: "ett hus → fyra ___",
            answer: "hus",
            explain: "Group 5: no plural ending at all.",
          },
          {
            kind: "blank",
            prompt: "en man → många ___",
            answer: "män",
            explain: "Vowel change, exactly like German Mann → Männer.",
          },
          {
            kind: "blank",
            prompt: "en bok → fem ___",
            answer: "böcker",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich habe zwei Kinder.",
            answer: "Jag har två barn",
            explain: "'barn' doesn't change in the plural.",
          },
        ],
      },
    ],
  },
  {
    id: "everyday-verbs",
    title: "Vardagsverb",
    titleDe: "Alltagsverben",
    emoji: "🏃",
    level: "A1",
    blurb: "The verbs you'll use every single day, in the present tense.",
    lessons: [
      {
        id: "present",
        title: "Presens",
        titleDe: "Das Präsens",
        intro:
          "Almost every Swedish verb ends in -r in the present tense, and it never changes for person. 'Jag talar, du talar, han talar' — one form, always.",
        grammarId: "present-tense",
        words: ["äta", "dricka", "gå", "komma", "se", "göra", "ta", "ge", "läsa", "skriva", "arbeta", "sova"],
        exercises: [
          {
            kind: "blank",
            prompt: "att äta → jag ___",
            answer: "äter",
          },
          {
            kind: "blank",
            prompt: "att gå → hon ___",
            answer: "går",
          },
          {
            kind: "blank",
            prompt: "att arbeta → vi ___",
            answer: "arbetar",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich trinke Kaffee.",
            answer: "Jag dricker kaffe",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Sie liest ein Buch.",
            answer: "Hon läser en bok",
          },
          {
            kind: "choice",
            prompt: "How do you say 'I am eating' (right now)?",
            options: ["Jag är äter", "Jag äter", "Jag är ätande", "Jag äter är"],
            answer: 1,
            explain: "Swedish has no continuous tense. 'Jag äter' covers both 'ich esse' and 'ich bin am Essen'.",
          },
        ],
      },
      {
        id: "modals",
        title: "Kan, vill, ska",
        titleDe: "Modalverben",
        intro:
          "Modal verbs work just like German ones: modal in second position, bare infinitive after it. Watch out for 'vill' — it means 'wollen', not the English future.",
        grammarId: "modal-verbs",
        words: ["kunna", "vilja", "ska", "måste", "få", "böra"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich kann schwimmen.",
            answer: "Jag kan simma",
          },
          {
            kind: "choice",
            prompt: "Which is correct?",
            options: ["Jag vill att äta", "Jag vill äta", "Jag vill äter", "Jag vill till äta"],
            answer: 1,
            explain: "Modal verbs take a bare infinitive — no 'att', just as German takes no 'zu'.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich muss jetzt gehen.",
            answer: "Jag måste gå nu",
          },
          {
            kind: "choice",
            prompt: "'Es wird morgen regnen.' Which is right?",
            options: ["Det ska regna imorgon", "Det kommer att regna imorgon", "Det vill regna imorgon", "Det regnar ska imorgon"],
            answer: 1,
            explain: "Nobody decided the weather, so use 'kommer att'. 'Ska' implies intention.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Darf ich fragen?",
            answer: "Får jag fråga",
          },
        ],
      },
      {
        id: "negation",
        title: "Inte",
        titleDe: "Verneinung",
        intro:
          "One word does all your negating: 'inte'. In a main clause it goes right after the verb. That placement flips in subordinate clauses, but that's a later lesson.",
        grammarId: "negation",
        words: ["inte", "aldrig", "ingen", "inget", "inga"],
        exercises: [
          {
            kind: "order",
            prompt: "Build: 'I don't understand.'",
            tokens: ["Jag", "förstår", "inte"],
            answer: "Jag förstår inte",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Er kommt heute nicht.",
            answer: "Han kommer inte idag",
          },
          {
            kind: "choice",
            prompt: "'Ich habe kein Auto.' Which is correct?",
            options: ["Jag har inte en bil", "Jag har ingen bil", "Jag har inget bil", "Jag har inte bil"],
            answer: 1,
            explain: "'ingen' with en-words, 'inget' with ett-words, 'inga' with plurals.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich habe kein Geld.",
            answer: "Jag har inga pengar",
            explain: "'pengar' is plural-only in Swedish, so it takes 'inga'.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wir können jetzt nicht gehen.",
            answer: "Vi kan inte gå nu",
            explain: "'inte' follows the FINITE verb 'kan', not the infinitive 'gå'.",
          },
        ],
      },
    ],
  },
  {
    id: "numbers-time-unit",
    title: "Siffror och tid",
    titleDe: "Zahlen und Zeit",
    emoji: "🕐",
    level: "A1",
    blurb: "Counting, telling the time, and naming the days. Easier than German in one respect, identical in another.",
    lessons: [
      {
        id: "numbers",
        title: "Räkna",
        titleDe: "Zählen",
        intro:
          "Swedish reads numbers left to right: 21 is 'tjugoett', not 'einundzwanzig'. After years of German, this feels almost too easy.",
        grammarId: "numbers-time",
        words: ["noll", "ett", "två", "tre", "fyra", "fem", "sex", "sju", "åtta", "nio", "tio", "tjugo", "hundra", "tusen"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "einundzwanzig",
            answer: "tjugoett",
            explain: "Read forwards: tjugo (20) + ett (1).",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "fünfunddreißig",
            answer: "trettiofem",
          },
          {
            kind: "choice",
            prompt: "How many houses? '___ hus'",
            options: ["en", "ett"],
            answer: 1,
            explain: "The number 'one' agrees with the noun, just like the article.",
          },
          {
            kind: "listen",
            sv: "Det kostar tvåhundrafemtio kronor.",
            de: "Das kostet zweihundertfünfzig Kronen.",
          },
        ],
      },
      {
        id: "clock",
        title: "Klockan",
        titleDe: "Die Uhrzeit",
        intro:
          "Good news: 'halv fyra' means 3:30, exactly like German 'halb vier'. English speakers find this baffling; you already have the instinct.",
        grammarId: "numbers-time",
        words: ["klocka", "timme", "minut", "morgon", "kväll", "natt", "middag", "eftermiddag"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "halb vier",
            answer: "halv fyra",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Viertel nach drei",
            answer: "kvart över tre",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Viertel vor vier",
            answer: "kvart i fyra",
            explain: "'i' for 'to', 'över' for 'past'.",
          },
          {
            kind: "choice",
            prompt: "'halv fem' means:",
            options: ["5:30", "4:30", "5:00", "4:00"],
            answer: 1,
            explain: "Half way TO five, so 4:30 — the German logic, not the English one.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wie spät ist es?",
            answer: "Vad är klockan",
          },
        ],
      },
      {
        id: "days",
        title: "Dagar och månader",
        titleDe: "Tage und Monate",
        intro:
          "Weekdays and months are almost recognisable from German, with one spelling rule to remember: they're never capitalised in Swedish.",
        grammarId: "numbers-time",
        words: ["måndag", "tisdag", "onsdag", "torsdag", "fredag", "lördag", "söndag", "helg", "vecka", "månad", "år", "idag", "imorgon", "igår"],
        exercises: [
          {
            kind: "choice",
            prompt: "Which is written correctly?",
            options: ["på Måndag", "på måndag", "På Måndag", "pa mandag"],
            answer: 1,
            explain: "Weekdays are lowercase in Swedish, unlike German.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Bis morgen!",
            answer: "Vi ses imorgon",
            alts: ["vi ses imorgon!"],
          },
          {
            kind: "choice",
            prompt: "'i måndags' means:",
            options: ["next Monday", "last Monday", "every Monday", "on Mondays"],
            answer: 1,
            explain: "The -s form points backwards. 'på måndag' points forwards.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich arbeite am Samstag.",
            answer: "Jag jobbar på lördag",
            alts: ["jag arbetar på lördag"],
          },
        ],
      },
    ],
  },
  {
    id: "word-order-unit",
    title: "Ordföljd",
    titleDe: "Der Satzbau",
    emoji: "🧩",
    level: "A1",
    blurb: "The verb goes second. You already do this in German — but the rest of the sentence behaves differently.",
    lessons: [
      {
        id: "v2",
        title: "Verbet på plats två",
        titleDe: "Verbzweitstellung",
        intro:
          "Swedish is a V2 language just like German: exactly one element before the finite verb. If you start with a time expression, the subject moves behind the verb.",
        grammarId: "word-order-v2",
        words: ["idag", "imorgon", "igår", "nu", "sedan", "ofta", "alltid"],
        exercises: [
          {
            kind: "order",
            prompt: "Build: 'Today I am working.' Start with 'Idag'.",
            tokens: ["Idag", "jobbar", "jag"],
            answer: "Idag jobbar jag",
            explain: "'Idag' takes slot one, so the subject jumps behind the verb.",
          },
          {
            kind: "choice",
            prompt: "Which is correct?",
            options: ["Imorgon jag åker till Stockholm", "Imorgon åker jag till Stockholm", "Jag imorgon åker till Stockholm", "Åker jag imorgon till Stockholm"],
            answer: 1,
          },
          {
            kind: "order",
            prompt: "Build: 'In the morning I drink coffee.'",
            tokens: ["På", "morgonen", "dricker", "jag", "kaffe"],
            answer: "På morgonen dricker jag kaffe",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Jetzt verstehe ich.",
            answer: "Nu förstår jag",
          },
        ],
      },
      {
        id: "verb-cluster",
        title: "Verben håller ihop",
        titleDe: "Keine Satzklammer",
        intro:
          "This is the big one. German sends infinitives and participles to the end of the sentence. Swedish keeps the whole verb phrase together near the front. Breaking this habit takes practice.",
        grammarId: "word-order-v2",
        words: ["vilja", "kunna", "ska", "köpa", "åka"],
        exercises: [
          {
            kind: "choice",
            prompt: "'Ich will morgen ein neues Auto kaufen.' Which Swedish version is right?",
            options: [
              "Jag vill imorgon en ny bil köpa",
              "Jag vill köpa en ny bil imorgon",
              "Jag imorgon vill köpa en ny bil",
              "Köpa vill jag en ny bil imorgon",
            ],
            answer: 1,
            explain: "The infinitive stays right after the modal. No verb at the end.",
          },
          {
            kind: "order",
            prompt: "Build: 'We are going to travel to Stockholm on Friday.'",
            tokens: ["Vi", "ska", "åka", "till", "Stockholm", "på", "fredag"],
            answer: "Vi ska åka till Stockholm på fredag",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Sie hat das Buch gelesen.",
            answer: "Hon har läst boken",
            explain: "'har läst' stays together. German splits them; Swedish doesn't.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich möchte einen Kaffee bestellen.",
            answer: "Jag vill beställa en kaffe",
            alts: ["jag skulle vilja beställa en kaffe"],
          },
        ],
      },
    ],
  },
  {
    id: "describing",
    title: "Beskriva saker",
    titleDe: "Dinge beschreiben",
    emoji: "🎨",
    level: "A1",
    blurb: "Adjectives, colours, and the double-definiteness rule that will haunt you for months.",
    lessons: [
      {
        id: "adjectives",
        title: "Adjektiv",
        titleDe: "Adjektive",
        intro:
          "Three forms per adjective: base for en-words, +t for ett-words, +a for plurals and definite forms. Compared to German's case endings, this is almost restful.",
        grammarId: "adjectives",
        words: ["stor", "liten", "ny", "gammal", "bra", "dålig", "vacker", "dyr", "billig", "snabb", "varm", "kall"],
        exercises: [
          {
            kind: "blank",
            prompt: "en ___ bil (groß)",
            answer: "stor",
          },
          {
            kind: "blank",
            prompt: "ett ___ hus (groß)",
            answer: "stort",
          },
          {
            kind: "blank",
            prompt: "två ___ bilar (groß)",
            answer: "stora",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Das Haus ist groß.",
            answer: "Huset är stort",
            explain: "Even after 'är', the adjective agrees. German doesn't do this.",
          },
          {
            kind: "blank",
            prompt: "ett ___ barn (klein)",
            answer: "litet",
            explain: "'liten' is irregular: liten / litet / små.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Die Autos sind teuer.",
            answer: "Bilarna är dyra",
          },
        ],
      },
      {
        id: "double-definite",
        title: "Dubbel bestämdhet",
        titleDe: "Doppelte Bestimmtheit",
        intro:
          "When a definite noun has an adjective, Swedish marks it twice: an article in front AND the suffix on the noun. 'Den stora bilen'. Forgetting either half is the single most common German-speaker error.",
        grammarId: "definite-forms",
        words: ["den", "det", "de", "stor", "ny", "gammal"],
        exercises: [
          {
            kind: "choice",
            prompt: "'das große Haus' in Swedish:",
            options: ["det stora hus", "stora huset", "det stora huset", "det stort huset"],
            answer: 2,
            explain: "Front article 'det' + adjective in -a + noun with the suffix.",
          },
          {
            kind: "choice",
            prompt: "'das neue Auto' in Swedish:",
            options: ["den nya bilen", "den ny bilen", "den nya bil", "nya bilen"],
            answer: 0,
          },
          {
            kind: "blank",
            prompt: "___ gamla huset (das alte Haus)",
            answer: "det",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "die großen Autos",
            answer: "de stora bilarna",
          },
          {
            kind: "choice",
            prompt: "'mein neues Auto' in Swedish:",
            options: ["min nya bilen", "min nya bil", "den min nya bilen", "mitt nya bil"],
            answer: 1,
            explain: "After a possessive, the noun stays indefinite. No suffix, no front article.",
          },
        ],
      },
      {
        id: "colors",
        title: "Färger",
        titleDe: "Farben",
        intro: "Colours behave like any other adjective, and several are near-identical to German.",
        words: ["röd", "blå", "gul", "grön", "svart", "vit", "grå", "brun", "rosa", "lila", "färg"],
        exercises: [
          {
            kind: "blank",
            prompt: "ett ___ hus (rot)",
            answer: "rött",
          },
          {
            kind: "blank",
            prompt: "en ___ bil (blau)",
            answer: "blå",
          },
          {
            kind: "choice",
            prompt: "Which colour adjective never changes form?",
            options: ["röd", "grön", "rosa", "vit"],
            answer: 2,
            explain: "'rosa', 'lila' and 'orange' are invariable.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Die Blume ist gelb.",
            answer: "Blomman är gul",
          },
        ],
      },
    ],
  },
  {
    id: "family-unit",
    title: "Familj",
    titleDe: "Familie",
    emoji: "👨‍👩‍👧",
    level: "A1",
    blurb: "Family words, possessives, and the sin/sitt/sina distinction German simply doesn't have.",
    lessons: [
      {
        id: "family-words",
        title: "Familjen",
        titleDe: "Die Familie",
        intro:
          "Swedish is precise about grandparents: 'mormor' is your mother's mother, 'farfar' your father's father. Once you see the pattern it's far clearer than German 'Oma'.",
        words: ["familj", "mamma", "pappa", "syster", "bror", "barn", "son", "dotter", "mormor", "farmor", "morfar", "farfar", "vän", "kompis", "sambo"],
        exercises: [
          {
            kind: "choice",
            prompt: "'mormor' is:",
            options: ["father's mother", "mother's mother", "mother's father", "father's father"],
            answer: 1,
            explain: "mor + mor = mother's mother. The logic is completely transparent.",
          },
          {
            kind: "choice",
            prompt: "Your father's father is:",
            options: ["morfar", "farfar", "farmor", "mormor"],
            answer: 1,
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich habe zwei Schwestern.",
            answer: "Jag har två systrar",
          },
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Han är min sambo.",
            answer: "Er ist mein Lebenspartner.",
            explain: "'sambo' means an unmarried live-in partner — a legally recognised status in Sweden.",
          },
        ],
      },
      {
        id: "possessives",
        title: "Min, din, sin",
        titleDe: "Possessivpronomen",
        intro:
          "'Min/mitt/mina' agrees with the thing owned. Then there's 'sin', which has no German equivalent: it means 'his/her own' and points back to the subject. Getting it wrong changes who owns what.",
        grammarId: "possessives",
        words: ["min", "mitt", "mina", "din", "ditt", "dina", "hans", "hennes", "vår", "deras", "sin", "sitt", "sina"],
        exercises: [
          {
            kind: "blank",
            prompt: "___ bil (mein Auto)",
            answer: "min",
          },
          {
            kind: "blank",
            prompt: "___ hus (mein Haus)",
            answer: "mitt",
          },
          {
            kind: "choice",
            prompt: "'Er nimmt sein eigenes Buch.'",
            options: ["Han tar hans bok", "Han tar sin bok", "Han tar sitt bok", "Han tar sina bok"],
            answer: 1,
            explain: "The book belongs to the subject, so use 'sin'. 'bok' is an en-word.",
          },
          {
            kind: "choice",
            prompt: "'Er nimmt das Buch von jemand anderem.'",
            options: ["Han tar sin bok", "Han tar hans bok", "Han tar sitt bok", "Han tar boken sin"],
            answer: 1,
            explain: "Someone else's book, so 'hans'. This distinction doesn't exist in German.",
          },
          {
            kind: "choice",
            prompt: "Which is correct?",
            options: ["min bilen", "min bil", "den min bil", "min bilar"],
            answer: 1,
            explain: "After a possessive the noun stays indefinite.",
          },
        ],
      },
    ],
  },
  {
    id: "food-unit",
    title: "Mat och fika",
    titleDe: "Essen und Fika",
    emoji: "☕",
    level: "A1",
    blurb: "Order food, survive a cafe, and understand why 'fika' is not just a coffee break.",
    lessons: [
      {
        id: "food-words",
        title: "Mat och dryck",
        titleDe: "Essen und Trinken",
        intro:
          "Food vocabulary, plus two traps: 'glass' means ice cream (not a drinking glass), and saying 'jag är full' tells people you're drunk, not that you've eaten enough.",
        words: ["mat", "vatten", "kaffe", "te", "mjölk", "öl", "vin", "bröd", "ost", "ägg", "kött", "fisk", "frukt", "grönsak", "glass", "kaka", "bulle"],
        exercises: [
          {
            kind: "choice",
            prompt: "'glass' in Swedish means:",
            options: ["a drinking glass", "ice cream", "glasses", "a window"],
            answer: 1,
            explain: "A drinking glass is 'ett glas' with one s. The vowel length differs too.",
          },
          {
            kind: "choice",
            prompt: "You've eaten enough. What do you say?",
            options: ["Jag är full", "Jag är mätt", "Jag är hungrig", "Jag är törstig"],
            answer: 1,
            explain: "'Full' means drunk in Swedish. 'Mätt' is what you want.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich möchte einen Kaffee, bitte.",
            answer: "Jag vill ha en kaffe, tack",
            alts: ["en kaffe, tack", "jag skulle vilja ha en kaffe, tack"],
            explain: "'tack' does the job of 'bitte' when ordering.",
          },
          {
            kind: "listen",
            sv: "Vill du ha mjölk i kaffet?",
            de: "Möchtest du Milch im Kaffee?",
          },
        ],
      },
      {
        id: "at-the-cafe",
        title: "På kaféet",
        titleDe: "Im Café",
        intro:
          "'Fika' is a verb and a noun: coffee, something sweet, and — crucially — company. Declining a fika invitation is a small social event in itself.",
        words: ["fika", "beställa", "nota", "meny", "kopp", "tallrik", "smaka", "gott", "hungrig", "törstig", "mätt"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Die Rechnung, bitte.",
            answer: "Notan, tack",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Was kostet das?",
            answer: "Vad kostar det",
          },
          {
            kind: "choice",
            prompt: "A colleague says 'Ska vi fika?' They're proposing:",
            options: ["a formal meeting", "coffee and a chat", "lunch at a restaurant", "going home"],
            answer: 1,
          },
          {
            kind: "speak",
            sv: "Hej! Jag skulle vilja ha en kaffe och en kanelbulle, tack.",
            de: "Hallo! Ich hätte gern einen Kaffee und eine Zimtschnecke, bitte.",
          },
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Det var jättegott!",
            answer: "Das war sehr lecker!",
          },
        ],
      },
    ],
  },
];
