import type { Unit } from "./types";

export const COURSE_B1: Unit[] = [
  {
    id: "opinions",
    title: "Åsikter och känslor",
    titleDe: "Meinungen und Gefühle",
    emoji: "💭",
    level: "B1",
    blurb: "Say what you think, how you feel, and why — with the connectors that hold an argument together.",
    lessons: [
      {
        id: "opinions",
        title: "Vad tycker du?",
        titleDe: "Seine Meinung sagen",
        intro:
          "Swedish separates 'tycka' (opinion), 'tro' (belief) and 'veta' (knowledge). Using 'tycker' for a fact sounds odd, and using 'vet' for an opinion sounds arrogant.",
        words: ["tycka", "tro", "veta", "anse", "åsikt", "tanke", "idé", "hålla med", "tvivla", "verkligen", "faktiskt", "egentligen"],
        exercises: [
          {
            kind: "choice",
            prompt: "'Ich finde, dass der Film gut ist.' (opinion)",
            options: ["Jag vet att filmen är bra", "Jag tycker att filmen är bra", "Jag tror att filmen är bra", "Jag anser filmen bra"],
            answer: 1,
            explain: "'tycka' = personal taste or opinion. 'tro' would mean you suspect it's good without having seen it.",
          },
          {
            kind: "choice",
            prompt: "'Ich glaube, es regnet morgen.' (belief about a fact)",
            options: ["Jag tycker att det regnar imorgon", "Jag tror att det regnar imorgon", "Jag vet att det regnar imorgon", "Jag anser att det regnar imorgon"],
            answer: 1,
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich stimme dir zu.",
            answer: "Jag håller med dig",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich bin nicht sicher, ob das eine gute Idee ist.",
            answer: "Jag är inte säker på om det är en bra idé",
            explain: "Note 'säker på' — the preposition is fixed.",
          },
          {
            kind: "speak",
            sv: "Jag tycker att det är en bra idé, men jag är lite osäker.",
            de: "Ich finde, das ist eine gute Idee, aber ich bin etwas unsicher.",
          },
        ],
      },
      {
        id: "connectors",
        title: "Bindeord",
        titleDe: "Verknüpfungen",
        intro:
          "The words that turn a list of sentences into an argument. Most have near-exact German equivalents, so this is mostly a vocabulary job rather than a grammar one.",
        words: ["dessutom", "däremot", "istället", "särskilt", "till exempel", "å ena sidan", "å andra sidan", "alltså", "dock", "ändå", "tack vare", "på grund av", "trots att"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "außerdem",
            answer: "dessutom",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "obwohl es regnet",
            answer: "trots att det regnar",
            alts: ["fast det regnar", "fastän det regnar"],
          },
          {
            kind: "choice",
            prompt: "'wegen des Wetters'",
            options: ["tack vare vädret", "på grund av vädret", "trots vädret", "istället för vädret"],
            answer: 1,
            explain: "'på grund av' is neutral cause; 'tack vare' implies the cause was positive.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Einerseits ist es teuer, andererseits ist es gut.",
            answer: "Å ena sidan är det dyrt, å andra sidan är det bra",
          },
        ],
      },
    ],
  },
  {
    id: "passive-unit",
    title: "Passiv och finnas",
    titleDe: "Passiv und es gibt",
    emoji: "🔄",
    level: "B1",
    blurb: "The s-passive, deponent verbs, and 'det finns' — three things Swedish does that German has no direct parallel for.",
    lessons: [
      {
        id: "s-passive",
        title: "S-passiv",
        titleDe: "Das s-Passiv",
        intro:
          "Add -s to the verb and you have a passive. Swedish uses this constantly, especially in writing, signs and instructions — far more than German uses 'werden'.",
        grammarId: "passive",
        words: ["bygga", "sälja", "öppna", "stänga", "göra", "skriva"],
        exercises: [
          {
            kind: "blank",
            prompt: "Huset ___ nu. (bygga, s-passive present)",
            answer: "byggs",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Das Buch wurde von Astrid Lindgren geschrieben.",
            answer: "Boken skrevs av Astrid Lindgren",
            explain: "The agent takes 'av', never 'från' or 'genom'.",
          },
          {
            kind: "choice",
            prompt: "A shop sign reads 'Öppnas klockan 10'. It means:",
            options: ["Open at 10", "Opens at 10 (is opened)", "Opened at 10", "Closes at 10"],
            answer: 1,
          },
          {
            kind: "choice",
            prompt: "Which describes a STATE rather than an event?",
            options: ["Dörren blev stängd", "Dörren är stängd", "Dörren stängdes", "Dörren stänger"],
            answer: 1,
            explain: "'är' + participle = the resulting state. 'blev' = the event of it happening.",
          },
        ],
      },
      {
        id: "finnas",
        title: "Det finns",
        titleDe: "Es gibt",
        intro:
          "'Det finns' is your 'es gibt'. And it belongs to a small family of verbs that always end in -s without being passive at all: hoppas, trivas, minnas, lyckas.",
        grammarId: "passive",
        words: ["finnas", "hoppas", "trivas", "minnas", "lyckas", "andas", "umgås"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Es gibt hier viele Cafés.",
            answer: "Det finns många caféer här",
          },
          {
            kind: "choice",
            prompt: "'Es gibt keinen Kaffee mehr.'",
            options: ["Det är inget kaffe kvar", "Det finns inget kaffe kvar", "Det ger inget kaffe kvar", "Det har inget kaffe kvar"],
            answer: 1,
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich hoffe, dass du gut ankommst.",
            answer: "Jag hoppas att du kommer fram bra",
            explain: "'hoppas' always ends in -s, in every tense.",
          },
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Jag trivs verkligen i Sverige.",
            answer: "Ich fühle mich in Schweden wirklich wohl.",
          },
          {
            kind: "choice",
            prompt: "'Wir sehen uns!'",
            options: ["Vi ser oss!", "Vi ses!", "Vi ser!", "Vi sett!"],
            answer: 1,
            explain: "The -s form here is reciprocal: 'see each other'.",
          },
        ],
      },
      {
        id: "relative",
        title: "Relativsatser",
        titleDe: "Relativsätze",
        intro:
          "One word, 'som', replaces the entire German relative pronoun system. The catch: the preposition moves to the end of the clause.",
        grammarId: "relative-clauses",
        words: ["som", "vars", "vilket", "där", "dit"],
        exercises: [
          {
            kind: "choice",
            prompt: "'Der Mann, mit dem ich gesprochen habe.'",
            options: ["Mannen med som jag pratade", "Mannen som jag pratade med", "Mannen med vilken jag pratade", "Mannen som med jag pratade"],
            answer: 1,
            explain: "Swedish strands the preposition at the end. German never does this.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Das Haus, in dem wir wohnen.",
            answer: "Huset som vi bor i",
          },
          {
            kind: "choice",
            prompt: "In which sentence can 'som' be dropped?",
            options: ["Mannen som bor här", "Boken som jag läste", "Bilen som står där", "Kvinnan som ringde"],
            answer: 1,
            explain: "'som' is droppable only when it's the object of the relative clause.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Die Stadt, in der ich wohne.",
            answer: "Staden där jag bor",
          },
        ],
      },
    ],
  },
  {
    id: "hypothetical",
    title: "Om jag kunde",
    titleDe: "Konjunktiv",
    emoji: "🔮",
    level: "B1",
    blurb: "Hypotheticals with 'skulle', polite requests, and the one surviving subjunctive: 'vore'.",
    lessons: [
      {
        id: "conditional",
        title: "Skulle",
        titleDe: "Würde",
        intro:
          "Swedish has no Konjunktiv II paradigm to memorise. The condition uses a plain preterite and the consequence uses 'skulle'. That's the whole system.",
        grammarId: "conditional",
        words: ["skulle", "om", "vore", "gärna", "kanske"],
        exercises: [
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wenn ich Geld hätte, würde ich ein Auto kaufen.",
            answer: "Om jag hade pengar skulle jag köpa en bil",
            explain: "Plain preterite 'hade' in the om-clause — no special subjunctive form.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Könntest du mir helfen?",
            answer: "Skulle du kunna hjälpa mig",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Ich möchte bestellen.",
            answer: "Jag skulle vilja beställa",
          },
          {
            kind: "choice",
            prompt: "'Das wäre nett.'",
            options: ["Det vore trevligt", "Det var trevligt", "Det är trevligt", "Det blir trevligt"],
            answer: 0,
            explain: "'vore' is the last real subjunctive in Swedish. 'skulle vara' also works.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wenn ich es gewusst hätte, wäre ich gekommen.",
            answer: "Om jag hade vetat skulle jag ha kommit",
          },
        ],
      },
      {
        id: "posture",
        title: "Sitta, stå, ligga",
        titleDe: "Positionsverben",
        intro:
          "Swedish insists on saying how something is positioned. Books lie, bottles stand, keys sit in locks. Using 'är' where a Swede would say 'ligger' marks you as foreign immediately.",
        grammarId: "posture-verbs",
        words: ["sitta", "stå", "ligga", "sätta", "ställa", "lägga", "hänga"],
        exercises: [
          {
            kind: "choice",
            prompt: "'Das Buch liegt auf dem Tisch.'",
            options: ["Boken är på bordet", "Boken ligger på bordet", "Boken står på bordet", "Boken sitter på bordet"],
            answer: 1,
          },
          {
            kind: "choice",
            prompt: "'Die Flasche steht im Kühlschrank.'",
            options: ["Flaskan ligger i kylskåpet", "Flaskan står i kylskåpet", "Flaskan sitter i kylskåpet", "Flaskan är i kylskåpet"],
            answer: 1,
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Wo liegt Stockholm?",
            answer: "Var ligger Stockholm",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Sie liest gerade.",
            answer: "Hon sitter och läser",
            explain: "'sitta och' + verb is Swedish's way of marking an ongoing action.",
          },
          {
            kind: "blank",
            prompt: "Jag ___ boken på bordet. (legen — transitive)",
            answer: "lägger",
            explain: "'lägga' is the transitive partner of 'ligga', like legen/liegen.",
          },
        ],
      },
    ],
  },
  {
    id: "advanced",
    title: "Nyanser",
    titleDe: "Feinheiten",
    emoji: "✨",
    level: "B2",
    blurb: "Discourse particles, compounds, and the errors that mark you as a German speaker.",
    lessons: [
      {
        id: "particles",
        title: "Ju, väl, nog",
        titleDe: "Modalpartikeln",
        intro:
          "These tiny words carry attitude, and German has near-exact equivalents. Using them is the single fastest way to stop sounding like a textbook.",
        grammarId: "particles-discourse",
        words: ["ju", "väl", "nog", "då", "alltså", "faktiskt", "förstås", "visst"],
        exercises: [
          {
            kind: "choice",
            prompt: "'Das ist ja wahr.'",
            options: ["Det är väl sant", "Det är ju sant", "Det är nog sant", "Det är då sant"],
            answer: 1,
            explain: "'ju' = German 'ja': appeals to what you both already know.",
          },
          {
            kind: "choice",
            prompt: "'Du kommst doch?' (seeking agreement)",
            options: ["Du kommer ju?", "Du kommer väl?", "Du kommer nog?", "Du kommer då?"],
            answer: 1,
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Er kommt wohl bald.",
            answer: "Han kommer nog snart",
          },
          {
            kind: "choice",
            prompt: "'nog' is a false friend for English 'enough'. How do you say 'groß genug'?",
            options: ["nog stor", "stor nog", "tillräckligt nog", "nog tillräckligt"],
            answer: 1,
            explain: "'stor nog' or 'tillräckligt stor'. As a sentence adverb, 'nog' means 'probably'.",
          },
        ],
      },
      {
        id: "compounds",
        title: "Sammansatta ord",
        titleDe: "Komposita",
        intro:
          "Swedish glues nouns together exactly like German, and splitting them is the most mocked error in the language. Here your German instinct is simply correct — trust it.",
        grammarId: "compounds",
        words: ["sommarstuga", "kylskåp", "vardagsrum", "sjukhus", "flygplats", "barnbarn", "huvudvärk", "lösenord"],
        exercises: [
          {
            kind: "choice",
            prompt: "Which is written correctly?",
            options: ["en rök fri miljö", "en rökfri miljö", "en rök-fri miljö", "en rök fri-miljö"],
            answer: 1,
            explain: "Split it and 'rök' reads as a command to smoke. Swedes find this hilarious and slightly painful.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Küchentisch",
            answer: "köksbord",
            explain: "kök + s + bord. The linking -s appears in many compounds.",
          },
          {
            kind: "choice",
            prompt: "'ett barnbarn' is:",
            options: ["a child's child, i.e. a grandchild", "a small child", "two children", "a childish person"],
            answer: 0,
          },
          {
            kind: "choice",
            prompt: "What determines the gender of a compound?",
            options: ["the first element", "the last element", "the longest element", "always en"],
            answer: 1,
            explain: "The head is on the right, exactly as in German.",
          },
        ],
      },
      {
        id: "german-errors",
        title: "Tyska fällor",
        titleDe: "Typische Fehler",
        intro:
          "A checklist of the mistakes German speakers reliably make. Worth revisiting every few weeks — these are habits, not knowledge gaps.",
        grammarId: "german-interference",
        words: ["rolig", "lugn", "öl", "glass", "full", "mätt", "semester", "snäll", "snabb", "nog"],
        exercises: [
          {
            kind: "choice",
            prompt: "'rolig' means:",
            options: ["ruhig", "lustig", "traurig", "schnell"],
            answer: 1,
            explain: "'ruhig' is 'lugn'. This false friend catches every German speaker at least once.",
          },
          {
            kind: "choice",
            prompt: "'snäll' means:",
            options: ["schnell", "lieb/nett", "schlau", "seltsam"],
            answer: 1,
            explain: "'schnell' is 'snabb'.",
          },
          {
            kind: "choice",
            prompt: "Which sentence is correct?",
            options: [
              "Jag är gått hem",
              "Jag har gått hem",
              "Jag är gick hem",
              "Jag har gick hem",
            ],
            answer: 1,
            explain: "Always 'har'. The haben/sein split doesn't exist in Swedish.",
          },
          {
            kind: "choice",
            prompt: "Which sentence is correct?",
            options: [
              "Jag vet att han imorgon kommer",
              "Jag vet att han kommer imorgon",
              "Jag vet att kommer han imorgon",
              "Jag vet att han imorgon kommer inte",
            ],
            answer: 1,
            explain: "No verb-final order in Swedish subordinate clauses.",
          },
          {
            kind: "choice",
            prompt: "'das neue Auto'",
            options: ["den nya bil", "nya bilen", "den nya bilen", "det nya bilen"],
            answer: 2,
            explain: "Double definiteness: front article AND suffix.",
          },
        ],
      },
      {
        id: "idioms",
        title: "Idiom",
        titleDe: "Redewendungen",
        intro:
          "Expressions that don't translate literally but make you sound like you actually live there. Several are gloriously strange.",
        words: ["det är lugnt", "det ordnar sig", "ta det lugnt", "håll tummarna", "hur som helst", "i stort sett", "så klart", "det spelar ingen roll"],
        exercises: [
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Det är ingen ko på isen.",
            answer: "Es besteht kein Grund zur Eile.",
            explain: "Literally 'there's no cow on the ice'. Peak Swedish.",
          },
          {
            kind: "translate",
            direction: "de-sv",
            prompt: "Daumen drücken!",
            answer: "Håll tummarna",
            explain: "Swedes hold their thumbs rather than crossing fingers — same gesture as Germans.",
          },
          {
            kind: "choice",
            prompt: "Someone apologises for being late. The most natural Swedish reply:",
            options: ["Det spelar ingen roll", "Det är lugnt", "Ingen fara", "All of these work"],
            answer: 3,
          },
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Smaken är som baken, delad.",
            answer: "Über Geschmack lässt sich streiten.",
          },
        ],
      },
      {
        id: "swedish-life",
        title: "Svenskt liv",
        titleDe: "Leben in Schweden",
        intro:
          "Words with no German equivalent that you'll meet in your first month: lagom, orka, hinna, slippa, fredagsmys. These are the ones that make Swedes say you actually speak the language.",
        words: ["lagom", "orka", "hinna", "slippa", "fredagsmys", "mysigt", "jobbig", "duktig", "fika", "allemansrätten", "personnummer", "systembolaget"],
        exercises: [
          {
            kind: "choice",
            prompt: "'Jag orkar inte' means:",
            options: ["I can't do it", "I don't have the energy for it", "I don't want to", "I don't understand"],
            answer: 1,
            explain: "'orka' is about having the energy, not the ability. There's no clean German equivalent.",
          },
          {
            kind: "choice",
            prompt: "'Hinner du?' asks:",
            options: ["Can you do it?", "Do you have time to make it?", "Do you want to?", "Do you understand?"],
            answer: 1,
          },
          {
            kind: "choice",
            prompt: "'Jag slipper jobba imorgon' means:",
            options: ["I have to work tomorrow", "I get out of working tomorrow", "I want to work tomorrow", "I forgot to work tomorrow"],
            answer: 1,
            explain: "'slippa' means being spared something. German needs a whole phrase for this.",
          },
          {
            kind: "translate",
            direction: "sv-de",
            prompt: "Det är lagom varmt idag.",
            answer: "Es ist heute angenehm warm.",
            explain: "'lagom' = exactly the right amount. Swedes will tell you it's untranslatable.",
          },
          {
            kind: "speak",
            sv: "Ikväll blir det fredagsmys — det ska bli mysigt!",
            de: "Heute Abend gibt es Fredagsmys — das wird gemütlich!",
          },
        ],
      },
    ],
  },
];
